# Generated by Django 5.2.3 on 2025-06-22 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='intruder_image/default_error.png', upload_to='intruder_image/%Y/%m/%d/'),
        ),
    ]
